### ISSUE TITLE
linkage group not valid term

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_cmap_loader#48]
we list it as as valid term in the loader, but it isnt

its invalid because synonyms wont work.  we need to either use the correct Chado API which replaces synonyms, or, not use the autocomplete that includes synonyms.

**Comment by bradfordcondon** [comment]
https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0000018

hmmm but linkage_group IS a valid term?

**Comment by jwest60** [comment]
update linkage group to linkage_group in the importer form description

**Comment by jwest60** [comment]
the description for the field now says linkage_group instead of the synonym
